### PR TITLE
cocMatrix optimization to solve allocation problems

### LINKED ISSUE #146: Error: cannot allocate vector of size n Mb
Hi,
I am obtaining an error when I run the `Co-occurrence Network` with all the default settings apart from the **Field** that I set to **Author's Keywords**.

### PR DESCRIPTION
**Pull request by ricber**
I select the n most frequent field's values at the beginning of the function to avoid creating a large matrix that causes memory allocation problems. This optimization also considerably reduces computational time. 

This pull request closes #146

### CODE REVIEW

**Comment by ricber** [comment]
This pull request raised issue #150

**Comment by ricber** [comment]
The pull request is completed and could be merged.

**Review by massimoaria — COMMENTED** [review]
Thanks for your work but the commit is incomplete and it breaks the other structure functions in biblioshiny.
Please, try to modify the intellectualStructure() and socialStructure() functions too.

**Comment by ricber** [comment]
> 
> 
> Thanks for your work but the commit is incomplete and it breaks the other structure functions in biblioshiny.
> Please, try to modify the intellectualStructure() and socialStructure() functions too.

I've extended the modifications to the intellectualStructure() and socialStructure() functions too.

**Pull request merged**
