### PR TITLE
Add host param

### PR DESCRIPTION
**Pull request by wuhanstudio**
Hi,

The docker image has been successfully built. But after deploying it to the cluster, it turns out the server listens on 127.0.0.1, thus it cannot be accessed outside the container.

    https://hub.docker.com/r/wuhanstudio/biblioshiny

Do you think it is OK to add another param host, so that it can listen on 0.0.0.0?

I'll rebuild the image and try to deploy it again.

    https://biblioshiny.wuhanstudio.team/

Thanks a lot.

### CODE REVIEW

**Comment by wuhanstudio** [comment]
Oh, sorry,  
I suddenly realize that I forget to ask, is it OK to publish such an image to docker hub?

It helps more people to try biblioshiny instantly with a single command:
    docker container run -p 8080:8080 wuhanstudio/biblioshiny

If you don't think it's OK, I'll remove the image, and sorry for publishing it without asking for your permission.

**Comment by massimoaria** [comment]
I have just added thee argument host to biblioshiny function.

I am not an expert of docker. 
So I don't know how to run biblioshiny from it.

**Comment by massimoaria** [comment]
I would like to know how to publish a shiny app as you did on https://biblioshiny.wuhanstudio.team/

**Comment by wuhanstudio** [comment]
> I have just added thee argument host to biblioshiny function.
> 
> I am not an expert of docker.
> So I don't know how to run biblioshiny from it.
> 
> I would like to know how publish a shiny app as you did on https://biblioshiny.wuhanstudio.team/

The website is hosted on AWS cloud server (Ubuntu 18.04, 1 CPU, 1G Memory). With docker installed, it's pretty straight forward to publish the app, only 4 commands in Ubuntu bash:

    docker swarm init
    docker network create --driver=overlay traefik-public
    docker stack deploy -c traefik-compose.yml traefik
    docker stack deploy -c biblioshiny-compose.yml biblioshiny

Then, https://biblioshiny.wuhanstudio.team/ is available

**Comment by wuhanstudio** [comment]
Here's the official documentation about installing docker on Ubuntu

https://docs.docker.com/install/linux/docker-ce/ubuntu/

And here are the two yml files:

[traefik-compose.yml]

    version: '3'

    services:
      traefik:
        # The official v2.0 Traefik docker image
        image: traefik:v2.0
        # Enables the web UI and tells Traefik to listen to docker
        command:
          #- "--api.insecure=true"
          - "--providers.docker=true"
          - "--providers.docker.swarmMode=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.web.address=:80"
          - "--entryPoints.websecure.address=:443"
          - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
          - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
          - "--certificatesresolvers.myhttpchallenge.acme.email=wuhanstudio@qq.com"
          - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
        ports:
          #- "8080:8080"
          - "80:80"
          - "443:443"
        volumes:
          # So that Traefik can listen to the Docker events
          - /var/run/docker.sock:/var/run/docker.sock
          - /mnt/data/letsencrypt:/letsencrypt
        networks:
          - traefik-public
        deploy:
          placement:
            constraints:
              - node.role == manager

    networks:
      traefik-public:
        external: true

[biblioshiny-compose.yml]

    version: '3'
    services:
      biblioshiny:
        image: wuhanstudio/biblioshiny:1.0.0
        networks:
         - traefik-public
        deploy:
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.bib.rule=Host(`biblioshiny.wuhanstudio.cc`)"
            - "traefik.http.routers.bib.entrypoints=web"
            - "traefik.http.services.bib.loadbalancer.server.port=8080"
            # TLS
            - "traefik.http.routers.bibs.rule=Host(`biblioshiny.wuhanstudio.cc`)"
            - "traefik.http.routers.bibs.entrypoints=websecure"
            - "traefik.http.routers.bibs.tls.certresolver=myhttpchallenge"
            # Redirect
            - "traefik.http.routers.bib.middlewares=https_redirect"
            - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
          placement:
            constraints:
              - node.role == worker
    networks:
      traefik-public:
        external: true

**Pull request closed without merging**
